### ISSUE TITLE
Fails when called from Yo

### ISSUE THREAD

**Issue by ghost** [Slashgear/generator-rancher-catalog#2]
node_modules/generator-rancher-catalog/generators/app/index.js:51
    this.props.clusterTypes.forEach(name => {
                                         ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as rancher-catalog:app] (/opt/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/opt/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/opt/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:21)

**Comment by Slashgear** [comment]
Hello, I can't reproduce your issue.
I'm on :

```
MacOS Sierra 10.12.3
node v7.7.1
npm 4.1.2
yo 1.8.5
```

Could you give me those kind of infos ?

**Comment by ghost** [comment]
MacOS El Capitain 10.11.6
node v0.12.7
npm 3.10.8
yo 1.8.5

**Comment by ghost** [comment]
Upgraded node to v7.7.4 and it now works correctly.

Many thanks
