### ISSUE TITLE
Exec command with error 

### ISSUE THREAD

**Issue by wilddylan** [Slashgear/generator-rancher-catalog#3]
```shell
[root@master ~]# yo rancher-catalog
/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:14)
    at Insight.get (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:197:48)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[root@master ~]#
```

centos 7.3
node/10.5.0

**Comment by Slashgear** [comment]
Hello, it's seems you have installed yeoman with sudo. So you can't use it without.

You have to change owner of yeoman.
